
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FLOAT_LIT = 47;
  public static final int CHAR_LIT = 45;
  public static final int INCREMENT = 29;
  public static final int CHAR = 11;
  public static final int EQUALS = 17;
  public static final int SEMI = 18;
  public static final int LSBRAC = 41;
  public static final int INT = 10;
  public static final int PRINTLN = 8;
  public static final int RBRAC = 40;
  public static final int MINUS = 30;
  public static final int DECREMENT = 28;
  public static final int TILDE = 34;
  public static final int GREATER_THAN = 24;
  public static final int LESS_GREATER = 27;
  public static final int RSBRAC = 42;
  public static final int RPAR = 38;
  public static final int VERTICAL_BARS = 20;
  public static final int BOOL = 12;
  public static final int COMMA = 19;
  public static final int CLASS = 15;
  public static final int FI = 4;
  public static final int DIV = 36;
  public static final int LESS_EQUAL = 25;
  public static final int PLUS = 31;
  public static final int IF = 2;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int GREATER_EQUAL = 26;
  public static final int error = 1;
  public static final int STR_LIT = 46;
  public static final int IDENT = 43;
  public static final int VOID = 16;
  public static final int TIMES = 35;
  public static final int COLON = 33;
  public static final int ELSE = 3;
  public static final int READ = 6;
  public static final int FINAL = 14;
  public static final int WHILE = 5;
  public static final int FLOAT = 13;
  public static final int BOOL_LIT = 48;
  public static final int LPAR = 37;
  public static final int QUESTION = 32;
  public static final int LBRAC = 39;
  public static final int AMPERSANDS = 21;
  public static final int LESS_THAN = 23;
  public static final int INT_LIT = 44;
  public static final int EQUAL_EQUAL = 22;
  public static final int PRINT = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "FI",
  "WHILE",
  "READ",
  "PRINT",
  "PRINTLN",
  "RETURN",
  "INT",
  "CHAR",
  "BOOL",
  "FLOAT",
  "FINAL",
  "CLASS",
  "VOID",
  "EQUALS",
  "SEMI",
  "COMMA",
  "VERTICAL_BARS",
  "AMPERSANDS",
  "EQUAL_EQUAL",
  "LESS_THAN",
  "GREATER_THAN",
  "LESS_EQUAL",
  "GREATER_EQUAL",
  "LESS_GREATER",
  "DECREMENT",
  "INCREMENT",
  "MINUS",
  "PLUS",
  "QUESTION",
  "COLON",
  "TILDE",
  "TIMES",
  "DIV",
  "LPAR",
  "RPAR",
  "LBRAC",
  "RBRAC",
  "LSBRAC",
  "RSBRAC",
  "IDENT",
  "INT_LIT",
  "CHAR_LIT",
  "STR_LIT",
  "FLOAT_LIT",
  "BOOL_LIT"
  };
}

