
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int BOOLLIT = 52;
  public static final int GREATERTHAN = 9;
  public static final int INCREMENT = 29;
  public static final int CHAR = 34;
  public static final int STRINGLIT = 51;
  public static final int UMINUS = 6;
  public static final int PERIOD = 19;
  public static final int UPLUS = 7;
  public static final int NOTEQUAL = 13;
  public static final int SEMI = 22;
  public static final int INT = 33;
  public static final int MINUS = 2;
  public static final int DECREMENT = 30;
  public static final int INTLIT = 48;
  public static final int RPAR = 24;
  public static final int LESSEQUAL = 10;
  public static final int LESSTHAN = 8;
  public static final int BOOL = 37;
  public static final int QMARK = 17;
  public static final int COMMA = 21;
  public static final int CLASS = 31;
  public static final int FI = 41;
  public static final int EQUALEQUAL = 12;
  public static final int DIV = 5;
  public static final int PLUS = 3;
  public static final int IF = 39;
  public static final int ASSIGN = 20;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int LNOT = 16;
  public static final int LAND = 15;
  public static final int PRINTLINE = 45;
  public static final int error = 1;
  public static final int LCURLY = 25;
  public static final int LOR = 14;
  public static final int IDENT = 47;
  public static final int VOID = 38;
  public static final int FLOATLIT = 50;
  public static final int RCURLY = 26;
  public static final int GREATEREQUAL = 11;
  public static final int TIMES = 4;
  public static final int CHARLIT = 49;
  public static final int COLON = 18;
  public static final int ELSE = 40;
  public static final int LSQUARE = 27;
  public static final int READ = 46;
  public static final int WHILE = 42;
  public static final int RSQUARE = 28;
  public static final int FINAL = 32;
  public static final int FLOAT = 35;
  public static final int STRING = 36;
  public static final int LPAR = 23;
  public static final int PRINT = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MINUS",
  "PLUS",
  "TIMES",
  "DIV",
  "UMINUS",
  "UPLUS",
  "LESSTHAN",
  "GREATERTHAN",
  "LESSEQUAL",
  "GREATEREQUAL",
  "EQUALEQUAL",
  "NOTEQUAL",
  "LOR",
  "LAND",
  "LNOT",
  "QMARK",
  "COLON",
  "PERIOD",
  "ASSIGN",
  "COMMA",
  "SEMI",
  "LPAR",
  "RPAR",
  "LCURLY",
  "RCURLY",
  "LSQUARE",
  "RSQUARE",
  "INCREMENT",
  "DECREMENT",
  "CLASS",
  "FINAL",
  "INT",
  "CHAR",
  "FLOAT",
  "STRING",
  "BOOL",
  "VOID",
  "IF",
  "ELSE",
  "FI",
  "WHILE",
  "RETURN",
  "PRINT",
  "PRINTLINE",
  "READ",
  "IDENT",
  "INTLIT",
  "CHARLIT",
  "FLOATLIT",
  "STRINGLIT",
  "BOOLLIT"
  };
}

